name: "Build and Deploy to ECS"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to deploy (dev/prod)'
        required: true
      deploy_secret:
        description: 'Secret name in AWS Secrets Manager'
        required: true
        


env:
  environment: ${{ github.event.inputs.environment }}
  aws_region: "ap-south-1"
  AWS_ACCOUNT: 059941826920
  ECS_CLUSTER_NAME: "dev-app-cluster"
  ECS_SERVICE_FLASK: "flask-service"
  ECS_SERVICE_NGINX: "nginx-service"
  ECS_SERVICE_REDIS: "redis-service"
  ECR_REPO_FLASK: "059941826920.dkr.ecr.ap-south-1.amazonaws.com/dev-app-flask"
  ECR_REPO_NGINX: "059941826920.dkr.ecr.ap-south-1.amazonaws.com/dev-app-nginx"
  ECR_REPO_REDIS: "059941826920.dkr.ecr.ap-south-1.amazonaws.com/dev-app-redis"
  ECS_TASK_DEF_FLASK: "dev-app-flask"
  ECS_TASK_DEF_NGINX: "dev-app-nginx"
  ECS_TASK_DEF_REDIS: "dev-app-redis"
  APP_CONTAINER_FLASK: "flask-container"
  APP_CONTAINER_NGINX: "nginx-container"
  APP_CONTAINER_REDIS: "redis-container"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: ecr login
        run: aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin ${{ env.aws_account }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

 # ===== Flask =====
      - name: Build and push Flask image
        run: |
          IMAGE=${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_FLASK }}:${TAG}
          docker build -t $IMAGE ./backend
          docker push $IMAGE
          echo "FLASK_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Render new Flask task definition
        id: taskdef-flask
        uses: aws-actions/amazon-ecs-render-task-definition@v2
        with:
          task-definition: ecs-task-defs/flask.json
          container-name: flask-container
          image: ${{ FLASK_IMAGE }}

      - name: Deploy Flask to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.taskdef-flask.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_FLASK }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true